include:
  - project: 'repos/releng/kokkuri'
    file: 'includes/images.yaml'

stages:
  - test

test:
  stage: test
  extends: .kokkuri:build-and-run-image
  parallel:
    matrix:
      - DISTRO: [buster, bullseye]
  variables:
    BUILD_VARIANT: test-$DISTRO
