include:
  - project: repos/releng/kokkuri
    file: includes/images.yaml
  - project: repos/releng/docpub
    file: includes/publish.yml

stages:
  - test
  - publish-dist
  - build-docs
  - publish-docs

verify-deps:
  stage: test
  extends: .kokkuri:build-and-run-image
  parallel:
    matrix:
      - DISTRO: &supported_distros [buster, bullseye, bookworm]
  variables:
    BUILD_VARIANT: verify-deps-$DISTRO

test-web:
  stage: test
  extends: .kokkuri:build-image
  variables:
    BUILD_VARIANT: test-web

test:
  stage: test
  extends: .kokkuri:build-image
  parallel:
    matrix:
      - DISTRO: *supported_distros
  variables:
    BUILD_VARIANT: test-$DISTRO-report
    BUILDCTL_BUILD_FLAGS: --output type=local,dest=test-reports
  artifacts:
    when: always
    reports:
      junit: test-reports/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: test-reports/coverage.xml
  coverage: /(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/

publish-dist:
  stage: publish-dist
  extends: .kokkuri:build-and-publish-image
  parallel:
    matrix:
      - DISTRO: *supported_distros
  variables:
    BUILD_VARIANT: binary-dist-$DISTRO
    PUBLISH_IMAGE_NAME: ${CI_PROJECT_PATH}/$DISTRO
    PUBLISH_IMAGE_TAG: $CI_COMMIT_TAG
    PUBLISH_IMAGE_EXTRA_TAGS: 'latest'
  tags:
    - trusted
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_REF_PROTECTED

.docs-job:
  rules:
    - if: $CI_PROJECT_PATH == "repos/releng/scap" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_REF_PROTECTED

build-docs:
  stage: build-docs
  extends:
    - .kokkuri:build-image
    - .docs-job
    - .docpub:build-docs
  variables:
    BUILD_VARIANT: docs
    # We'll end up with generated-documentation/docs/index.html, etc
    BUILDCTL_BUILD_FLAGS: --output type=local,dest=generated-documentation
    DOCS_DIR: generated-documentation/docs

publish-docs:
  stage: publish-docs
  extends:
    - .docs-job
    - .docpub:publish-docs
