stages:          # List of stages for jobs, and their order of execution
  - test

buster:
    stage: test
    image: docker-registry.wikimedia.org/python3-buster
    script:
        - apt-get update && apt-get install -y build-essential ca-certificates git libjpeg-dev openssl php-cli python3 python3-pip zlib1g-dev shellcheck
        - pip3 install -r requirements.txt test-requirements.txt docs/requirements.txt
        - scripts/check
