stages:
  - test

variables:
  DEBIAN_FRONTEND: noninteractive
  LANG: C.UTF-8

.script-common:
    script:
        # This is a rough translation of what scap's .pipeline/config.yaml and blubber.yaml result in.
        # FIXME: Redoing all these steps each time is very expensive compared to the actual testing time.
        - apt-get update
        - apt-get install -y build-essential ca-certificates git libjpeg-dev openssl php-cli python3 python3-pip python3-dev zlib1g-dev shellcheck
        - pip3 install -U setuptools!=60.9.0 
        - pip3 install -U wheel tox
        - pip3 install -U -r requirements.txt -r test-requirements.txt -r docs/requirements.txt
        - scripts/check

buster:
    extends: .script-common
    stage: test
    image: docker-registry.wikimedia.org/wikimedia-buster

bullseye:
    extends: .script-common
    stage: test
    image: docker-registry.wikimedia.org/bullseye