include:
  - project: 'repos/releng/kokkuri'
    file: 'includes/images.yaml'

stages:
  - test

build-buster-test-image:
  stage: test
  extends: .kokkuri:build-and-run-image
  variables:
    BUILD_VARIANT: buster-test

build-bullseye-test-image:
  stage: test
  extends: .kokkuri:build-and-run-image
  variables:
    BUILD_VARIANT: bullseye-test

# FIXME: Still need the equivalent of scap-tox-doc-docker
