include:
  - project: 'repos/releng/kokkuri'
    file: 'includes/images.yaml'

stages:
  - test
  - build-docs
  - publish-docs
  - publish-dist

verify-deps:
  stage: test
  extends: .kokkuri:build-and-run-image
  parallel:
    matrix:
      - DISTRO: [buster, bullseye]
  variables:
    BUILD_VARIANT: verify-deps-$DISTRO

test:
  stage: test
  extends: .kokkuri:build-and-run-image
  parallel:
    matrix:
      - DISTRO: [buster, bullseye]
  variables:
    BUILD_VARIANT: test-$DISTRO

.docs-job:
  tags:
    - trusted
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_REF_PROTECTED

build-docs:
  stage: build-docs
  extends:
    - .kokkuri:build-image
    - .docs-job
  variables:
    BUILD_VARIANT: docs
    # We'll end up with generated-documentation/docs/index.html, etc
    BUILDCTL_BUILD_FLAGS: --output type=local,dest=generated-documentation
  artifacts:
    paths:
      - generated-documentation
    expire_in: 1 hour

publish-docs:
  stage: publish-docs
  extends:
    - .docs-job
    - .kokkuri:publish-to-doc
  dependencies: [build-docs]
  variables:
    PUBLISH_TO_DOC_SOURCE: generated-documentation/docs
    PUBLISH_TO_DOC_DEST: scap

publish-dist:
  stage: publish-dist
  extends: .kokkuri:build-and-publish-image
  parallel:
    matrix:
      - DISTRO: [ buster, bullseye ]
  variables:
    BUILD_VARIANT: binary-dist-$DISTRO
    PUBLISH_IMAGE_NAME: ${CI_PROJECT_PATH}/$DISTRO
    PUBLISH_IMAGE_TAG: $CI_COMMIT_TAG
    PUBLISH_IMAGE_EXTRA_TAGS: 'latest'
  tags:
    - trusted
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_REF_PROTECTED
