#!/bin/bash

set -euo pipefail

title()
{
    echo
    echo =============================================================================
    echo "$@"
    echo
}

got()
{
    command -v "$1" > /dev/null
}


title "pytest (unit and other functional tests)"
python -m pytest -q

title "flake8 (coding style checks)"
flake8 --count --show-source --statistics \
       --ignore=W503,W605,E501,E203 \
       --exclude=.git,.tox,__pycache__,build,docs,dist,scap/sh.py,bin,subplot .

if got black
then
    # Black v18 is on Debian 10 (buster), but Lars develops on Debian
    # 11 (bullseye), which has a newer Black, which formats things
    # differently. So we only check formatting if we have a new Black.
    if black --version | grep -q 20
    then
        title "black (code formatting)"
        black --check --diff . bin/*
    fi
fi

if got sp-codegen
then
    title "Subplot (acceptance criteria)"
    rm -f test.log test.py
    sp-codegen scap.md -o test.py
    python3 test.py --log test.log --save-on-failure fail.tar.gz
fi

title "sphinx (documentation)"
sphinx-build -q -W -b html docs/ docs/_build/html


title "Oh happy day: all tests pass OK!"
exit 0
