#!/bin/bash

# Prints information about what versions of the scap deb are installed on
# deployment-prep hosts.

set -eu -o pipefail

function usage {
    cat <<EOF
Usage: $0 [ -v ]

-v: Enable verbose output

EOF
    exit 1
}

format=brief

while getopts "v" o; do
    case "${o}" in
        v)
            format=verbose
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

# Sudo to make sure we don't run as root (scap would fail)
remote_cmd='sudo -u scap scap version'

case "$format" in
    verbose)
        # shellcheck disable=SC2029
        ssh deployment-cumin.deployment-prep.eqiad.wmflabs \
            sudo cumin \
            --no-progress \
            --force \
            'P{C:scap}' \
            "'$remote_cmd'"
        ;;
    brief)
        # Alternate output which just shows all versions in use, w/o
        # the hostnames
        # shellcheck disable=SC2029
        ssh deployment-cumin.deployment-prep.eqiad.wmflabs \
            sudo cumin \
            --no-progress \
            --force \
            -o json \
            'P{C:scap}' \
            "'$remote_cmd'" \
            | grep -vF "_____FORMATTED_OUTPUT_____" | jq -r '.[]' | sort -u --version-sort
        ;;
    *)
        echo "Unknown format: $format"
        exit 1
        ;;
esac
