#!/bin/bash

set -eu -o pipefail

function usage {
    cat <<EOF
Usage: $0 [ version ]

Updates scap to the specified version on all deployment-prep hosts
that already have scap installed.  If the version is not supplied, the
latest code revision will be used.

EOF
    exit 1
}

version=

function confirm_latest_code_rev {
    local answer
    read -r -p "Update scap to latest code revision? " answer

    case "$answer" in
        y*)
            version="latest_rev"
            return
            ;;
        *)
            echo "Cancelled"
            exit 1
            ;;
    esac
}


if [ $# -eq 0 ]; then
    confirm_latest_code_rev
elif [ $# -eq 1 ]; then
    case "$1" in
        -h|--help)
            usage
            ;;
        *)
            version="$1"
            ;;
    esac
else
    usage
fi

if [ "$version" = latest_rev ]; then
  irc_message_ver='latest code revision'
  scap_tag=
else
  irc_message_ver=$version
  scap_tag="-t $version"
fi

cat <<EOF
Use this log message in #wikimedia-releng IRC:
!log Upgrading scap to $irc_message_ver in beta cluster
EOF

remote_cmd="
set -e
cd /srv/deployment/scap; git checkout master; git pull --rebase
bin/install_local_version.sh -u scap --on-deploy $scap_tag
cd; scap install-world --batch
"

encoded_remote_cmd=$(echo "$remote_cmd" | base64 -w0)

# shellcheck disable=SC2029
ssh deployment-deploy03.deployment-prep.eqiad1.wikimedia.cloud \
  "echo $encoded_remote_cmd | base64 -d | bash"
